[package]
name = "common_utils"
version = "0.1.0"
authors = ["David Cook <divergentdave@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33.3"
fs2 = "0.4.3"
libc = "0.2.81"
rand = "0.7.0"
sled = { path = "../sled" }
